var annotated_dup =
[
    [ "AbstractElement", "class_abstract_element.html", null ],
    [ "BuilderContainer", "class_builder_container.html", null ],
    [ "BuilderControlPanel", "class_builder_control_panel.html", null ],
    [ "BuilderControlsButtons", "class_builder_controls_buttons.html", null ],
    [ "CodeText", "class_code_text.html", null ],
    [ "ConditionalElement", "class_conditional_element.html", null ],
    [ "ConstantDecimalElement", "class_constant_decimal_element.html", null ],
    [ "ConstantTextElement", "class_constant_text_element.html", null ],
    [ "ContainerInformation", "struct_container_information.html", null ],
    [ "CustomElementInputDialog", "class_custom_element_input_dialog.html", null ],
    [ "DeleteItem", "class_delete_item.html", null ],
    [ "ElementDragEventHandler", "class_element_drag_event_handler.html", null ],
    [ "ElementManager", "class_element_manager.html", null ],
    [ "ElementsControlButtons", "class_elements_control_buttons.html", null ],
    [ "ElementsCreator", "class_elements_creator.html", null ],
    [ "ElementsLeftNavigator", "class_elements_left_navigator.html", null ],
    [ "ElementsListWidget", "class_elements_list_widget.html", null ],
    [ "ElementUserInputs", "class_element_user_inputs.html", null ],
    [ "ForLoopElement", "class_for_loop_element.html", null ],
    [ "IfLoopElement", "class_if_loop_element.html", null ],
    [ "ImageButton", "class_image_button.html", null ],
    [ "InputLabelDialog", "class_input_label_dialog.html", null ],
    [ "InternalDragEventHandler", "class_internal_drag_event_handler.html", null ],
    [ "JSONDataHandler", "class_j_s_o_n_data_handler.html", "class_j_s_o_n_data_handler" ],
    [ "MainAppWindow", "class_main_app_window.html", null ],
    [ "MainWindowUI", "class_main_window_u_i.html", null ],
    [ "OperationElement", "class_operation_element.html", null ],
    [ "ParameterUIBuilder", "class_parameter_u_i_builder.html", null ],
    [ "ReadVariableElement", "class_read_variable_element.html", null ],
    [ "ResultedTextView", "class_resulted_text_view.html", null ],
    [ "SearchBarWidget", "class_search_bar_widget.html", null ],
    [ "SettingsManager", "class_settings_manager.html", null ],
    [ "UserDefinedElement", "class_user_defined_element.html", null ],
    [ "WriteVariableElement", "class_write_variable_element.html", null ]
];