#ifndef BASICELEMENTTYPE_H
#define BASICELEMENTTYPE_H

enum class BasicElementType {
    UNKNOW,
    WRITE_VARIABLE,
    READ_VARIABLE,
    CONDITIONS,
    OPERATOR,
    CONSTANT,
    IF_LOOP,
    FOR_LOOP
};

#endif  // BASICELEMENTTYPE_H